[build]
  publish = "."
  functions = "netlify/functions"   # <— IMPORTANTE

# (opcional) si quieres poder abrir /return en el navegador para test
[[redirects]]
  from = "/return"
  to = "/.netlify/functions/niubiz-return"
  status = 200

[[redirects]]
  from = "/success.html"
  to = "/success.html"
  status = 200
  force = false

[[headers]]
  for = "/success.html"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
